Home: |md
# Home
- Will have a medium like home page
	- Hero page
	- Login and CTA button
|

Home -> Login

Login: |md
Standard Firebase Login
|

Login -> Dashboard

Dashboard: |md
# Dashboard
For you section
Featured Section
|

Dashboard -> Liked Posts

Liked Posts: List of posts which were liked by the user

Dashboard -> Post

Post: |md
- Title
- Content of post
- Likes
- Comments
|


Admin Login: |md
# Admin Login
store email of admin in db
|

Admin Login -> Admin Dashboard

Admin Dashboard: |md
- List of article_sources
- List of articles
- Create article_source
|

Admin Dashboard -> Article Source

Article Source: |md
- Trigger article source to create article
|
